export const eventsList = [
  {
    title: 'Essay Competition',
    desc: 'Nigeria @ 62, The good, the bad, and the way forward',
    date: '2022-10-22 10:00:am',
    location: 'Havarde College, Abeokuta',
    type: 'physical',
    image: '/events/1.jpg',
    socialUrl: '',
  },
  {
    title: 'Report Writing Workshop',
    desc: 'Workshop on seminar and project report writing for final year students of tertiary institutions. Graced by Lecturers and undergraduates from multiple institutions and marked by research grant awards.',
    date: '2023-01-14 10:00:am',
    location: 'Havarde College, Abeokuta',
    type: 'physical',
    image: '/events/2.jpg',
    socialUrl: '',
  },
  {
    title:
      'A discussion around the deficiencies in the Nigerian educational system',
    desc: 'A dive into the role of parents, the government, school authorities and the students in reaching a lasting solution.',
    date: '2023-08-16 04:30:pm',
    location: 'Zoom',
    type: 'virtual',
    image: '/events/3.jpg',
    socialUrl: 'https://youtube.com/live/vF0nfQEy6kM?feature=share',
  },
  {
    title: 'Legal Awareness Campaign - Student Rights',
    desc: 'Enlightenment on Students Rights.',
    date: '2023-09-20 4:30:pm',
    location: 'Zoom',
    type: 'virtual',
    image: '/events/4.jpg',
    socialUrl: 'https://www.youtube.com/live/BdiwT6EUlxM?si=vcaAp_A4KOa9ONGc',
  },
  {
    title: 'Legal Awareness Campaign - Employer-Employee Rights',
    desc: 'Employer-Employee Rights.',
    date: '2023-10-11 4:30:pm',
    location: 'Zoom',
    type: 'virtual',
    image: '/events/5.jpg',
    socialUrl: '',
  },
  {
    title: 'Legal Awareness Campaign - Landlord-Tenant Rights',
    desc: 'Landlord-Tenants Rights.',
    date: '2023-11-18 4:30:pm',
    location: 'Zoom',
    type: 'virtual',
    image: '/events/6.jpg',
    socialUrl: '',
  },
  {
    title: 'Talent Hunt',
    desc: '',
    date: '2024',
    location: '',
    type: '',
    image: '/events/7.jpg',
    socialUrl: '',
  },
]
