export const eventsList = [
  {
    title: 'Essay Competition',
    desc: 'Nigeria @ 62, The good, the bad, and the way forward',
    date: '2022-10-22 10:00:am',
    location: 'Havarde College, Abeokuta',
    type: 'physical',
    image: '/events/1.png',
    socialUrl: '',
  },
  {
    title: 'Report Writing Workshop',
    desc: 'Workshop on seminar and project report writing for final year students of tertiary institutions. Graced by Lecturers and undergraduates from multiple institutions and marked by research grant awards.',
    date: '2023-01-14 10:00:am',
    location: 'Havarde College, Abeokuta',
    type: 'physical',
    image: '/events/1.png',
    socialUrl: '',
  },
  {
    title:
      'A discussion around the deficiencies in the Nigerian educational system',
    desc: 'A dive into the role of parents, the government, school authorities and the students in reaching a lasting solution.',
    date: '2023-08-16 16:30:am',
    location: 'Zoom',
    type: 'virtual',
    image: '/events/1.png',
    url: 'https://youtube.com/live/vF0nfQEy6kM?feature=share',
  },
  {
    title: 'Legal Awareness Campaign',
    desc: 'Enlightenment on Students Rights.',
    date: '2023-09-20 16:30:am',
    location: 'Zoom',
    type: 'virtual',
    image: '/events/1.png',
    url: 'https://www.youtube.com/live/BdiwT6EUlxM?si=vcaAp_A4KOa9ONGc',
  },
  {
    title: 'Legal Awareness Campaign',
    desc: 'Employer-Employee Rights.',
    date: '2023-10-11 16:30:am',
    location: 'Zoom',
    type: 'virtual',
    image: '/events/1.png',
    url: '',
  },
  {
    title: 'Legal Awareness Campaign',
    desc: 'Landlord-Tenants Rights.',
    date: '2023-11-18 16:30:am',
    location: 'Zoom',
    type: 'virtual',
    image: '/events/1.png',
    url: '',
  },
]
